export const INCREMENT = 'HOMEPAGE/INCREMENT';
export const DECREMENT = 'HOMEPAGE/DECREMENT';

export const ASYNC_INCREMENT = 'HOMEPAGE/ASYNC_INCREMENT';
export const ASYNC_DECREMENT = 'HOMEPAGE/ASYNC_DECREMENT';

export const CANCEL = 'HOMEPAGE/CANCEL';
